### PR TITLE
Verify successful bind when creating pulp_rpmbind

### LINKED ISSUE #276: pulp_rpmbind resource creation 'succeeds' for repos that don't exist.
If you use `pulp_rpmbind` to bind to a non-existent repository, the resource should fail to apply.

The provider uses `pulp-consumer`, but the command returns 0 even when it fails.
```
[root@pulp ~]# pulp-consumer rpm bind --repo-id foobar
Repository [foobar] does not exist on the server

[root@pulp ~]# echo $?
0
```
This is with pulp 2.13.2.  Should I try to workaround this in https://github.com/Katello/puppet-pulp/blob/bb68da33dba2e4b4d106ef98aae7b0c9f248f012/lib/puppet/provider/pulp_rpmbind/consumer.rb#L48-L51 ?

### PR DESCRIPTION
**Pull request by alexjfisher**
Solves 2 problems
  * pulp-consumer rpm bind returns 0 even if the repo doesn't exist
  * Binding is asynchronous, so we should wait until it completes

Fixes #276

### CODE REVIEW

File: lib/puppet/provider/pulp_rpmbind/consumer.rb [hunk 1]
```diff
@@ -46,12 +46,26 @@ def exists?
...
     @property_hash[:ensure] = :present
   end
 
   def destroy
     consumer('rpm', 'unbind', '--repo-id', @resource[:name])
     @property_hash[:ensure] = :absent
   end
+
+  def wait_for_bind
+    tries ||= 10
```
Comment (ekohl) [inline lib/puppet/provider/pulp_rpmbind/consumer.rb]: I wonder if this should be configurable. What's your experience with how long the waiting typically takes?

Comment (alexjfisher) [reply lib/puppet/provider/pulp_rpmbind/consumer.rb]: During my testing, the process was actually very quick.  One 250ms wait was *always* enough for me. (IIRC I had to set the sleep to 0.01 to actually see more than one retry take place).  But I figured it might not always be that fast depending on what else the system was doing at the time or because of network congestion etc.  Waiting for no more than 2.5 seconds total seemed reasonable?  If it doesn't complete by then, there's probably no point waiting any longer??

Comment (ekohl) [reply lib/puppet/provider/pulp_rpmbind/consumer.rb]: That's fair and we can always fix it later.

**Comment by ekohl** [comment]
Thanks!
